### ISSUE TITLE
Unable to find spec for Cocoapods

### ISSUE THREAD

**Issue by VidurMalik** [SwiftKickMobile/SwiftMessages#11]
Great work on the library! 
Unfortunately, I'm unable to build the library using cocoapods. 
`pod "SwiftMessages"` results in 
`Analyzing dependencies
[!] Unable to find a specification for SwiftMessages`

Any guidance on this?

**Comment by VidurMalik** [comment]
In the interim, I'm using `pod "SwiftMessages", :git => 'https://github.com/SwiftKickMobile/SwiftMessages.git'`

**Comment by wtmoose** [comment]
You can search cocoapods.org and see that it's there. My only suggestion is make sure you're on CocoaPods 1.0.1 and that it's configured for CocoaPods.org and not an internal company repo or something like that. Otherwise, you'll probably better off asking CocoaPods since they list the repo as available.

**Comment by wtmoose** [comment]
Have you resolved this yet?

**Comment by whitepaperclip** [comment]
+1

**Comment by aaronbrethorst** [comment]
# Update to the latest released cocoapods gem
    [sudo] gem install cocoapods

    # Update the list of known cocoapods
    pod repo update

    # install!
    pod install

**Comment by wtmoose** [comment]
Closing this as it seems most certainly a CocoaPods configuration issue.

@aaronbrethorst Thanks for spelling out how to configure CocoaPods.
