### ISSUE TITLE
Pan gesture threshold control

### ISSUE THREAD

**Issue by tereks** [SwiftKickMobile/SwiftMessages#163]
Hello. I have SwiftMessages with duration == .forever but I'd like to be able to hide it via pan gesture. I see that TopBottomAnimation.closeSpeedThreshold cannot be set via config. How can I update this value?

**Comment by wtmoose** [comment]
That isn't something I'd want to make configurable. But I'd love to find the optimal value. What do you want to change it to and why?

**Comment by tereks** [comment]
I saw _open var closeSpeedThreshold_ in TopBottomAnimation and thought it left for further development. Can we create another Duration case or add closeSpeedThreshold param in Config and get this values via AnimationDelegate?

**Comment by wtmoose** [comment]
You didn't actually answer my question.

**Comment by tereks** [comment]
The answer to why is that I want to hide messageView with duration = .forever with pan gesture. And existing one is too quick

**Comment by wtmoose** [comment]
I'm asking you for specific parameter values that you want so I can consider changing the default.

**Comment by tereks** [comment]
Ok, got it. I don't want to just change the default value, because I need some flexibility on that issue. Closing issue

**Comment by wtmoose** [comment]
You can just use a custom instance of `TopBottomAnimation`:

````swift
let animation = TopBottomAnimation()
animation.closeSpeedThreshold = 1000
config.presentationStyle = .custom(animator: animation)
````

You'll want to pull the head of the master branch if you're displaying messages under top or bottom bars because I just fixed a layout bug when using `.custom`.

If you have parameters that you think work better than the defaults, I would appreciate if you would shared them here so I can consider changing the defaults.
