### ISSUE TITLE
Testing if SwiftyMessage is visible

### ISSUE THREAD

**Issue by emreoktem** [SwiftKickMobile/SwiftMessages#195]
I am preparing UI Tests for my IOS app and want to check if the message is shown correctly. 

I've already checked issue #167 but it works only if you know the contents of the message. 

In my case, the app shows an error message received from server and then, it will be great to have a more generic way to handle such requirements.

**Comment by wtmoose** [comment]
I'd probably use the same overall approach in #167, but with a predicate that utilizes the SwiftMessages APIs to ask what message is being displayed:
````
let predicate = NSPredicate { _, _ in
    return SwiftMessages.sharedInstance.current() != nil
}
````
I just noticed that there isn't a static version of the `current()` method, which is why I used `SwiftMessages.sharedInstance` in the above example.

If the message being queued is sufficient rather than strictly being displayed, you can use `currentOrQueued(id:)`, but you'll need to assign well-known `ids` to your messages since the default ones are derived from the content.
