### ISSUE TITLE
Setting Theme from Remote Push Notification

### ISSUE THREAD

**Issue by recoilnetworks** [SwiftKickMobile/SwiftMessages#26]
I need to set the theme of the message using a string being sent through a remote push notification. Unfortunately, when I am trying to set it I get this error:

Could not cast value of type 'NSTaggedPointerString' (0x102990630) to 'SwiftMessages.Theme'

Any ideas how I can get this to work? Here is my code:

    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        let notification = userInfo["aps"] as! [String: AnyObject]

        if (notification["content-available"] as? NSString)?.integerValue == 1 {
            // Silent
        } else {
            // Audible
            if (application.applicationState == UIApplicationState.active) {
                let view = MessageView.viewFromNib(layout: .MessageViewIOS8)
                view.configureTheme(notification["type"] as! Theme)
                view.configureDropShadow()
                view.configureContent(title: notification["title"] as! String, body: notification["alert"] as! String)
                SwiftMessages.show(view: view)
            } else {
                
            }
        }
    }

**Comment by nstefan** [comment]
This is more a stackoverflow type of question IMHO.
You need to convert the value of notification["type"] (apparently a String) to a Theme.
A solution could be to have a function like: themeFrom(_ type: String) -> Theme

**Comment by recoilnetworks** [comment]
How is this more of a StackOverflow question? This involves your plugin specifically. Man, whomever is replying to questions about this plugin is rude.

Thank you,

Adam L Miller | President / Owner | Recoil Networks, LLC
amiller@recoilnetworks.com | www.recoilnetworks.com

**Comment by wtmoose** [comment]
Your question can be boiled down to a general question "how do I convert a string into an enum in Swift?" Questions like this are typically asked on StackOverflow and the person who suggested as much (who isn't affiliated with SwiftMessages at all) was as polite as one could expect. Also, in your other post, I gave you my SO handle so that I could help you directly on that forum. Whether or not you agree with posting to SO, it seems like a small ask in return for someone else's time and expertise.
