### ISSUE TITLE
Massage View in Tabbar Controllers

### ISSUE THREAD

**Issue by murdeee** [SwiftKickMobile/SwiftMessages#266]
Hello, i have tabbar with 4 controllers and i want to show message view under navigation view by calling in viewDidLoad/viewWillAppear. But when i call it in 1 of controllers, i tap on another and nothing happens. Also i tried .hideAll() before call SwiftMessages.show(config: config, view: view) but it doesn't helped.

**Comment by wtmoose** [comment]
Can you add screenshots and code? I’m having trouble visualizing your problem.

**Comment by murdeee** [comment]
> Can you add screenshots and code? I’m having trouble visualizing your problem.

 I've investigated this issue, message view ( same on both controllers ) isn't showing in 2 controllers

**Comment by murdeee** [comment]
Test project:[url=https://radikal.ru][img]https://d.radikal.ru/d30/1812/8c/41e0d0935e30.png[/img][/url]
`    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        BannerController.showTopBanner(with: "Test1", type: .alert)
    }`
in both controllers

**Comment by wtmoose** [comment]
That code snippet isn't particularly helpful since you didn't include the implementation of `showTopBanner`. Can you include that or better yet attach the test project?

**Comment by wtmoose** [comment]
Your two messages have the same content "Test1" and thus the same `id`. By default, SwiftMessages ignores duplicate IDs. You can add this to `showBanner(withText:)`:

````swift
config.ignoreDuplicates = false
````

You probably also want to set:

````swift
SwiftMessages.pauseBetweenMessages = 0
````

To avoid delays when switching tabs. This also prevents a message from being displayed in the wrong tab if the user switches tabs faster than the default pause (since you're not explicitly stating where a message should be displayed using `config.presentationContext`.

As an alternative to the above workarounds, you might consider using a unique instance of SwiftMessages for each tab so that you aren't sharing a common message queue between tabs.

**Comment by Coeur** [comment]
It's a good answer @wtmoose. I believe you can close that issue now.
