### ISSUE TITLE
Message Top Padding

### ISSUE THREAD

**Issue by recoilnetworks** [SwiftKickMobile/SwiftMessages#27]
Is there anyway to push the message down from the top? I want the message to be be shown below my applications header.

**Comment by wtmoose** [comment]
The answer is most likely yes, but a couple of things:

1. You need to elaborate more because I'm having a hard time visualizing exactly what you want. How about a mockup?
2. Ask for help on Stackoverflow.com where others with similar questions can find and benefit from the discussion. This is not an appropriate forum. If you mention @timothymoose in a comment, I'll see it. And please [read this before posting](http://stackoverflow.com/help/how-to-ask).

**Comment by recoilnetworks** [comment]
Um, I know how to use StackOverflow so you don’t need to be rude and give me the guidelines/rules for posting. Now, which question are you referring to that I posted because I have two questions that are apparently both closed now. Interesting because other developers of plugins have been nice enough to assist me instead of turning me away to StackOverflow.

Thank you,

Adam L Miller | President / Owner | Recoil Networks, LLC
amiller@recoilnetworks.com | www.recoilnetworks.com
