### ISSUE TITLE
Not showing under custom uinavigationbar

### ISSUE THREAD

**Issue by libern** [SwiftKickMobile/SwiftMessages#281]
Currently I am using a custom navigationbar: https://github.com/Pircate/EachNavigationBar

If I use it instead of system one, I could not see the banner display under the custom navigation bar.

![image](https://user-images.githubusercontent.com/1830640/52163157-2d593f00-2719-11e9-94ac-0c01e29fbc7d.png)

Is there any solution?

Here is the demo project:

[Shark.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/2824305/Shark.zip)

**Comment by narendrajagne** [comment]
can you assign me this issue ?

**Comment by wtmoose** [comment]
@libern sorry somehow I missed this issue. Closing, however, because it is solvable without any updates. You can provide a container view to host the message using the configuration option `config.presentationContext = .view(_)`. You can place the container view such that the message appears to come from under the custom nav bar.
