### ISSUE TITLE
SwiftMessages 7.0.1 error

### ISSUE THREAD

**Issue by timbms** [SwiftKickMobile/SwiftMessages#345]
With SwiftMessages 7.0.1 and Xcode 11 I see an error though the UIWindowScene is protected with an availability check: 

```
@available(iOS 13, *)
func install(becomeKey: Bool, scene: UIWindowScene?) {
``` 

> Use of undeclared type 'UIWindowScene'

**Comment by wtmoose** [comment]
Well, `UIWindowScene` is declared in iOS 13 and this availability check should hide the API from lower iOS versions.

So it seems that that you’re (a) not on iOS 13 and (b) the `@availability` check isn’t hiding the API as it should. This is what people on Xcode 10 were seeing.

Could you please double check your Xcode version? Otherwise, it would help if you could describe your project setup as it relates to iOS SDKs. If you could attach a sample project that fails, that would be great.

**Comment by timbms** [comment]
I have double checked. I still had an Xcode 10 that was interfering here. Sorry for the confusion. 
And thanks for your fast response.

**Comment by wtmoose** [comment]
Glad you got it fixed.
