### ISSUE TITLE
Strange Keyboard behavior on presenting view

### ISSUE THREAD

**Issue by bellots** [SwiftKickMobile/SwiftMessages#36]
The problem raises when I'm editing a textfield and I show an alert.

The keyboard disappears while it shows the popup and automatically appears on its dismiss.

**Comment by wtmoose** [comment]
Please check #23

**Comment by wtmoose** [comment]
Assuming this is resolved.

**Comment by hebertialmeida** [comment]
The #23 partially solve this, is there a way to show the Message on top of NavigationController and do not hide and show the keyboard?

**Comment by wtmoose** [comment]
@hebertialmeida Sure, you can either do:
````swift
config.presentationContext = .viewController(navigationController)
````
or
````swift
config.presentationContext = .view(navigationController.view)
````
I've updated the documentation to help clarify the behavior of `.viewController` presentation context:

````swift
/**
 Displays the message view under navigation bars and tab bars if an
 appropriate bar is found. The search for bars starts with the given
 view controller's `parent` continues up the containment heirarchy
 until there are no more parents. If no bars are found, the message is
 displayed in the given view controller's view. This option can be used
 for targeted placement in a view controller heirarchy. Note, that because
 the search for bars starts with the parent, specifying a navigation 
 controller will not result in the message being displayed under that
 controller's navigation bar. One would instead need to specify one of
 the navigation controller's descendants.
*/
case viewController(_: UIViewController)
````

**Comment by hebertialmeida** [comment]
In my case this do not solve, I want to show it on same position as `.window(windowLevel: UIWindowLevelStatusBar)`.

The problem with `.window(windowLevel:..` is that it hides the keyboard and show again. So I switched to `.viewController(self)` or `.viewController(navigationController!)` as your said. It do not show on same position as specified on docs.

The position I want:
![img_1362](https://cloud.githubusercontent.com/assets/103670/21148925/f83b3782-c140-11e6-9b03-27df047d07db.PNG)

Where it shows:
![img_1363](https://cloud.githubusercontent.com/assets/103670/21148954/0576c434-c141-11e6-8d34-83021f722756.PNG)

**Comment by wtmoose** [comment]
@hebertialmeida Yes, you're absolutely right. The current behavior doesn't match my intention. But I'm going to leave it alone for now because you can still use:
````swift
config.presentationContext = .view(navigationController.view)
````
However, there are a couple of caveats with this approach:

1. The message will slide under the status bar. If you need to slide over, then you'll need to use `.window(windowLevel: .statusBar)`. And to do that without dismissing the keyboard is an entirely different issue. If you want to open a new ticket for that, I'll take a look.
2. The automatic adjustment made to avoid overlapping the status bar was not working with `.view()` presentation context. I've promoted a fix to the head of master that fixes this by improving the status bar collision detection. With this fix in place, the message will not overlap the status bar, but it will be positioned slightly lower than what you get with `.window(windowLevel: .statusBar)`.

**Comment by hebertialmeida** [comment]
This last fix from master is much better for me. I will create a issue for the keyboard dismissing thing.
