### ISSUE TITLE
Full width bottom card in iOS 13 (7.0.1 version) 

### ISSUE THREAD

**Issue by vivek4292** [SwiftKickMobile/SwiftMessages#388]
How can I use full width bottom card using 7.0.1 version. 
Here is my code. 

var config = SwiftMessages.defaultConfig
config.presentationStyle = .bottom
config.duration = .forever
config.dimMode = .none
config.interactiveHide = false
let view = MessageView.viewFromNib(layout: .cardView) 
view.configureTheme(theme, iconStyle: .default)
SwiftMessages.show(config: config, view: view)

**Comment by wtmoose** [comment]
What is the problem?

**Comment by vivek4292** [comment]
![2020-04-08](https://user-images.githubusercontent.com/34335017/79484627-9765b780-8031-11ea-973c-4c6e0ae8bb56.png)

This is how it's being displayed with your latest release. Before that it was like in below screenshot.
![IMG_0916](https://user-images.githubusercontent.com/34335017/79484900-04794d00-8032-11ea-9d7e-a2f0aa13e77e.PNG)

Did no changes in code at all. Just using your latest release and this happened.

**Comment by wtmoose** [comment]
Gotcha. The design was changed for iPad because the card spanning the full width on iPad isn't a good design.

If you want a different design, copy `CardView.xib` into your project and modify it. What you'd want to do is remove the constraint overrides for regular size class on the `CornerRoundingView`.
