### ISSUE TITLE
presentationStyle.center is not centered horizontally on iPad

### ISSUE THREAD

**Issue by willnix86** [SwiftKickMobile/SwiftMessages#402]
When using `presentationStyle = .center`, my custom card view shows up perfectly centered on mobile, but on iPad it is only centered vertically. Horizontally, the view sits on the left-hand side of the screen rather than completely centered

**Comment by wtmoose** [comment]
You on the latest version?

**Comment by willnix86** [comment]
Using 7.0.1

**Comment by wtmoose** [comment]
You need to update

**Comment by willnix86** [comment]
Just updated and still seeing the same issue, sadly.

This is how I'm creating the Message:

```
var config = SwiftMessages.Config()
    config.presentationStyle = .center
    config.dimMode = self.theme == .darkMode ? .color(color: UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 0.2), interactive: true) : .gray(interactive: true)
    config.duration = .forever
    config.interactiveHide = false
    
    let view: StartersView = try! SwiftMessages.viewFromNib(named: "CustomCardView")
    view.backgroundView.backgroundColor = theme.primary
    view.contentView.backgroundColor = .clear
    view.collectionView.backgroundColor = .clear
    
    let startersCollectionView = UICollectionView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())
    view.collectionView = startersCollectionView
    
    SwiftMessages.show(config: config, view: view)
```

**Comment by wtmoose** [comment]
Looks like you're using a custom nib file? I suggest taking look at the demo app to verify that the issue doesn't exist there and then take a look at your custom nib.

**Comment by wtmoose** [comment]
I'll take a look at the nib file if you attach it

**Comment by willnix86** [comment]
That's very kind of you, thank you! Still a bit of a noob when it comes to xibs, so that could be the issue


[CustomCardView.xib.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/4962002/CustomCardView.xib.zip)

**Comment by wtmoose** [comment]
It looks like you based your nib file on `CardView.xib`.

`CardView.xib` is designed to have different layouts in compact width size class (iPhone) and regular width size class (iPad). The iPhone layout is full width within the margins while the iPad layout is centered and hugs the content up to a maximum 500pt width.

These layouts are accomplished by constraints on the top-level view as well as a "<= 500 width" constraint on the background view in regular width size class for iPad.

It looks like you've modified these constraints quite a bit, with one of the side effects being left alignment on iPad. This particular issue is because you've got a leading constraint being installed for iPad when it is only supposed to be installed for iPhone.

I'm not sure why you made those changes, but if you're not that familiar with Auto Layout in Interface Builder, my suggestion is go back and make the constraints on the top-level view exactly match `CardView.xib`. Once you've done this, if you still can't achieve the layout you want, describe the layout to me and attach your updated xib file and I'll make further suggestions.

**Comment by willnix86** [comment]
I see - I'm trying to add the extra constraints that I remove / messed up based on the CardView.xib. Annoyingly, I don't see a way to add any new constraints. None of the constraint buttons at the bottom allow me to add them, and don't see a way to add them in the right hand panel. I'm sure I'm being dense, but I feel like there must be a way to add missing bottom/trailing constraints?

**Comment by willnix86** [comment]
Ok I fixed it - ended up just copying and tweaking the source code based on the CardView xib.

Thank you SO much for your help. this is amazing!
