### ISSUE TITLE
SwiftMessages showed only once when Config.duration = .forever

### ISSUE THREAD

**Issue by giofid** [SwiftKickMobile/SwiftMessages#411]
Hi @wtmoose, 
I try to briefly describe a potential problem found in the library. 
I have a view controller `V1` that presents (modally) a view controller `V2`, and `V2` shows a swifty-message with duration set to `.forever`. If `V2` is dismissed and presented again, when it tries to show again the same swifty-message, nothing appears. 

I attach a sample project: [SMExample.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/5218945/SMExample.zip)

As a workaround (honestly, it looks like an ugly workaround), I have to call `hide(animated:)` before to show the swifty-message and I have to call `show(config:, view:)` into `DispatchQueue.main.async`.
```        
SwiftMessages.hide(animated: false)
DispatchQueue.main.async {
    SwiftMessages.show(config: config, view: view)
}
```

I don't know if this problem is related to this one: #328.

**Comment by wtmoose** [comment]
If you are using the global SwiftMessages instance, your first message will block the queue until you dismiss it. SwiftMessages does not attempt to detect when a message should be dismissed sooner than the timing you specified.

You have a couple of options:

1. Explicitly dismiss the message when the view controller is being dismissed
2. Have your view controller create and use a unique instance of `SwiftMessages` so that the queue is local to the view controller.

Hope that helps.

**Comment by giofid** [comment]
Ok. I will use option 2. It seems the most clean one. 

Thank you Timothy.
