### ISSUE TITLE
KeyboardTrackingView causes a small space under bottom-style view

### ISSUE THREAD

**Issue by kientux** [SwiftKickMobile/SwiftMessages#483]
When I add `KeyboardTrackingView` to config and show a `bottom`-style view, there is a small space under it.

```swift
let messageView = BaseView(frame: .zero)

let backgroundView = CornerRoundingView()
backgroundView.cornerRadius = 12
backgroundView.layer.masksToBounds = true
messageView.installBackgroundView(backgroundView)

let contentView = UIView(frame: CGRect(x: 0, y: 0, width: 320, height: 128))
contentView.backgroundColor = .white
messageView.installContentView(contentView)

messageView.layoutMarginAdditions = .zero
messageView.respectSafeArea = false

var config = SwiftMessages.defaultConfig
config.keyboardTrackingView = KeyboardTrackingView()
config.dimMode = .color(color: UIColor(white: 0, alpha: 0.55), interactive: true)

config.presentationStyle = .bottom
config.duration = .forever
config.interactiveHide = false

config.presentationContext = .window(windowLevel: .statusBar)

// alertPresenter = SwiftMessages()
alertPresenter.show(config: config, view: messageView)
```

`respectSafeArea = false` is for iPhone with notch so we can clearly see it. I tried on normal iPhones and this still happens.

Screenshots:

With `KeyboardTrackingView`:

![Simulator Screen Shot - iPhone 11 - 2021-09-29 at 16 14 19](https://user-images.githubusercontent.com/4200743/135240041-d616d520-ec91-4c05-a935-bc66eca65120.png)

Without:

![Simulator Screen Shot - iPhone 11 - 2021-09-29 at 16 14 06](https://user-images.githubusercontent.com/4200743/135240047-86227f26-4b76-4943-9283-bffb62f93d13.png)

**Comment by wtmoose** [comment]
Can you try the `work/9.0.5` branch?

Here's an explanation if you're interested. By default, the bottom presentation places the message view 5pt below the screen so that the spring animation doesn't show a gap under the view when it overshoots. This behavior is intended for cases where the message view has a background color. However, you're using a clear message view with a background view that provides the visible region of the view. The background view's constraints negate the 5pt offset, so it aligns with the bottom of the screen. However, when you add the keyboard tracking view, the entire message view, along with the background view, is pushed up by 5pt.

You can fix this by setting the following:

````swift
messageView.bounceAnimationOffset = 0
````

But on the `work/9.0.5` branch, I've accounted for `bounceAnimationOffset` with the keyboard tracking view, so the above setting isn't needed.

**Comment by kientux** [comment]
Thank you, I tried the `work/9.0.5` branch and it worked as expected. Anyway, I use a custom `TopBottomAnimation` to disable the spring damping so setting `bounceAnimationOffset = 0` also do the work.
