### ISSUE TITLE
Add Privacy manifests file

### ISSUE THREAD

**Issue by yasiraliraj** [SwiftKickMobile/SwiftMessages#546]
Hello Team,

I hope this message finds you well. I would like to draw your attention to an important update required by the App Store. Starting May 1, 2024, a privacy manifest will be mandatory for all apps. Given the ongoing development and support for your SDK, integrating this feature would be highly beneficial for ensuring compliance with the new App Store guidelines. This addition would greatly help developers like us in continuing to provide seamless services through our applications. We appreciate your attention to this matter and look forward to any updates you can provide.

Thank you for your continued support.

**Comment by wtmoose** [comment]
Are you up for submitting a PR?

**Comment by yasiraliraj** [comment]
@wtmoose Please check the PR: https://github.com/SwiftKickMobile/SwiftMessages/pull/547

**Comment by SunZhiC** [comment]
In the Apple forums, as indicated by a DTS engineer, it is recommended [not adding an empty privacy manifest for no reason](https://developer.apple.com/forums/thread/746481?answerId=782256022#782256022).

**Comment by wtmoose** [comment]
Interesting. That seems like a bad design. There’s no way to distinguish between a library that doesn’t need a manifest from one that does, but hasn’t added one yet.🤦‍♂️

**Comment by mobru** [comment]
@wtmoose do you intend to merge the above mentioned PR?

**Comment by wtmoose** [comment]
@mobru no. Did you read through the comments? I don’t see any case for adding it

**Comment by mobru** [comment]
@wtmoose I did, yeah. But looking a the proposed Privacy Manifest [here](https://github.com/SwiftKickMobile/SwiftMessages/pull/547/commits/5d3f0de121f2e659015de4d20b6fd4bf97f6387f), it looks like it would not be empty, and therefore required. Or am I misunderstanding something here (and sorry if so)?

**Comment by wtmoose** [comment]
@mobru my fault. I assumed it was empty and didn't read the file. I don't know where @yasiraliraj came up with those items. I can't think of any reason why the SwiftMessages manifest would not be empty. I'll give @yasiraliraj  a chance to justify the changes and then close the PR.

**Comment by muruganandham** [comment]
+1

**Comment by wtmoose** [comment]
@muruganandham I have no idea what “+1” means in the context of this conversation. Could you elaborate?

**Comment by jznadams** [comment]
FWIW this is the best explanation of the rules that we have found in the Apple documentation so far:

- You need to include a privacy manifest file in your third-party SDK if it’s listed in “SDKs that require a privacy manifest and signature,” in [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/). 
- Otherwise, include a privacy manifest file in your third-party SDK if it uses required reasons API, collects data about the person using apps that include the third-party SDK, enables the app to collect data about people using the app, or contacts tracking domains.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

So sounds to me that if you don't use a required reasons API you don't need a manifest in the library.

**Comment by wtmoose** [comment]
@jznadams! Yeah we don’t need one
