### ISSUE TITLE
Conflict with R.swift

### ISSUE THREAD

**Issue by xiaosongshu** [SwiftKickMobile/SwiftMessages#70]
Getting `"MessageView" is  not a member type of Swift Messages`. All I did was drop a copy of MessageType.xib into my project, delete the titleLabel from the xib, and try to compile.

Screenshot:
![screen shot 2017-02-18 at 10 53 42 pm](https://cloud.githubusercontent.com/assets/1562135/23100122/6817ecdc-f62d-11e6-85f8-d47b5a9aa9f2.png)

**Comment by wtmoose** [comment]
This is the same as #56, which is to say that you can't qualify a SwiftMessages type with the framework name because it conflicts with `SwiftMessages` class. So when you say `SwiftMessages.MessageView`, it is looking for `MessageView` as a nested type in the `SwiftMessages` class.

I'm going to fix this by renaming the `SwiftMessages` class. But this is a breaking change and I don't plan to make it until the next major update.

The simple fix is to reference `MessageView` without qualifying it. If, for some reason you can't do that because of a conflict, you can add a file like this to your project:

````swift
import SwiftMessages
struct SwiftMessagesFix {
    typealias MessageViewFix = MessageView
}
````

And in your code do `SwiftMessagesFix.MessageViewFix` as an alias for `SwiftMessages.MessageView`.

**Comment by xiaosongshu** [comment]
Hi @wtmoose, thanks for the quick reply!

Sorry, but first time hearing the phrase, what does 

> The simple fix is to reference MessageView without qualifying it

mean exactly?

Regarding your second solution, when you say 

> do SwiftMessagesFix.MessageViewFix as an alias for SwiftMessages.MessageView.

you're talking about placing this in my code snippet screenshot I attached above right? If so, that won't quite work either as the file I'm showing is R.generated, which is automatically compiled and overwritten each time I build the project (so any changes would be lost)

**Comment by wtmoose** [comment]
Gotcha, I didn't realize that was auto-generated code.

By "without qualifying" I meant that you should just write `MessageView` instead of `SwiftMessages.MessageView`. But since this is auto-generated code, my suggestion is to subclass `MessageView` in your project:
````swift
class MyMessageView: MessageView {}
````
and reference `MyMessageView` instead of `MessageView` in your custom .xib file. If you have additional conflicts, such as image references, I suggest copying the images into your project or supplying your own images.

Let me know if you need more help with a workaround.

**Comment by xiaosongshu** [comment]
Ah, appreciate the clarification!

Regarding your suggestion, that was actually one of the approaches I tried last night! I tried doing it both via:

```
// Instantiate MessageView from a named nib.
let view: MessageView = try! SwiftMessages.viewFromNib(named: "MyCustomNib")

// Instantiate MyCustomView from a nib named MyCustomView.nib.
let view: MyCustomView = try! SwiftMessages.viewFromNib()
```

And while I got the project to compile properly, for some reason, the custom cell just didn't want to load. Instead of getting my custom cell, I would instead get the .info themed cell.

I gave it another shot just now and miraculously everything is working! I still have no idea what I did differently, but I think it might have been because I was subclassing MessageView, loading a custom view from (`viewFromNib`), but then also hiding the title/icons via code, when the custom cell didn't have those labels. Honestly, I scratched my head on it for quite some time last night, but all is swell now. Thank you!
