### ISSUE TITLE
App Rejection

### ISSUE THREAD

**Issue by FrancoisObob** [SwiftKickMobile/SwiftMessages#72]
Hello,

based on that topic : https://github.com/cruffenach/CRToast/issues/140
I was wondering if using a permanent status bar SwiftMessages view when internet connexion is lost (reachability .notReachable) will get my app rejected by Apple ?

Thanks ! Love your lib btw :)

**Comment by YacineVC** [comment]
Up

**Comment by wtmoose** [comment]
Thanks for bringing this up. I haven't used SwiftMessages and that way, so my comments are purely speculation. It sounds like the guideline in question is this one:

>People expect the status bar to be consistent systemwide. Don’t replace it with a custom status bar.

I could see how your case could lead to a rejection since you plan to show a persistent bar. The one thing working in your favor is that your's is an error condition, which is unlikely to be seen by the reviewer.

The rejection you linked to seems more like the developer got unlucky with an over zealous reviewer, given that the message was only covering the status bar for a fraction of a second.

As an alternative, have you considered using `UIWindowLevelNormal`? Your message bar will be a bit taller, but you won't obscure the status bar. The orange bar in the collage at the top of the readme shows that this looks like.

Hope that helps.

**Comment by FrancoisObob** [comment]
Hello,

Thank you for your answer. 

I tried with `UIWindowLevelNormal`, looks great but every user interaction is disable on the app when it appears, even with `dimMode = .none`

Is there a trick to keep user interactions enabled ?

**Comment by wtmoose** [comment]
Hmmm. That shouldn't happen. Can you reproduce that in the demo app? What version are you using?

**Comment by FrancoisObob** [comment]
Version : 3.3.0

```
let view = MessageView.viewFromNib(layout: .StatusLine)
view.configureContent(body: "Hello world !")
var config = SwiftMessages.Config()
config.presentationStyle = .top
config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)
config.duration = .forever
config.dimMode = .none
config.interactiveHide = false
config.preferredStatusBarStyle = .lightContent
SwiftMessages.show(config: config, view: view)
```

**Comment by FrancoisObob** [comment]
Works perfectly in 3.2.1 !

**Comment by wtmoose** [comment]
OK, thanks. I'll see what's up with 3.0.0.

**Comment by wtmoose** [comment]
Could you give 3.3.1 a try?

**Comment by FrancoisObob** [comment]
All good for me on 3.3.1, thanks !
