### ISSUE TITLE
How SwiftMessages can be installed manually?

### ISSUE THREAD

**Issue by moonvader** [SwiftKickMobile/SwiftMessages#87]
I want to figure out - how this repo can be installed manually (without cocoapods)?
I just copied SwiftMessages folder from SwiftMessages-master to my project and added this code

```
let myWiew = MessageView.viewFromNib(layout: .cardView)
SwiftMessages.show(view: myWiew)
```

and i got error: 

`_Unknown class _TtC13SwiftMessages11MessageView in Interface Builder file._
Failed to set (bounceAnimationOffset) user defined inspected property on (UIView)`

What am i doing wrong?

**Comment by wtmoose** [comment]
I've never tried this and don't have time to work on it right now.

But my guess is that it's because the MessageView element in the nib file reference the SwiftMessages module. You could try removing this module references from the nib file.

<img width="264" alt="screen shot 2017-04-19 at 10 32 30 pm" src="https://cloud.githubusercontent.com/assets/2529176/25212481/1bcf10d8-2550-11e7-8940-27016c55501b.png">

I'll leave this ticket open as a todo to try and make this work out-of-the-box.

**Comment by wtmoose** [comment]
This should be fixed on the head of master if you're interested in taking a look.

**Comment by wtmoose** [comment]
3.5.0
