### ISSUE TITLE
If navigationBar is hidden, presentationContex not works as expected

### ISSUE THREAD

**Issue by D-Link13** [SwiftKickMobile/SwiftMessages#88]
I have created my own errorView from xib... and I need to show it under a status bar, if my navigation bar is hidden, otherwise - under navigation bar.
I am facing a problem here: if navBar is hidden, than presentationContex .automatic and .viewController(self) shows me this view right over a status bar.

Also I noticed that I can't check if my VC has a navBar or is it hidden, in a config "body". Of course it's because I am declaring this var's like so, but maybe you know a workaround..

Here is my code:
```
lazy var errorView: ErrorView = {
        let view: ErrorView = try! SwiftMessages.viewFromNib()
        view.preferredHeight = 35.0
        return view
    }()
    
lazy var config: SwiftMessages.Config = {
// this is what i mean, when I say "body"
        var _config = SwiftMessages.defaultConfig
        _config.duration = .automatic
        _config.presentationStyle = .top
        _config.presentationContext = .automatic
        return _config
    }()
```

Any suggestions? Please

**Comment by wtmoose** [comment]
Hi. I don't get what the problem is from your description. I've test messages with navigation bar hidden and they behave as expected. It would help if you sent me a sample project and/or screenshots.

If you want the config to vary based on the state of your app, then I'd recommend either using a factory method:

````swift
func messageConfig(parameterThatAffectsConfig: SomeType) -> SwiftMessages.Config {
    // create and return config here
}
````

Or modifying a copy of the config before using it:

````swift
var someConfig = config
// modify someConfig here
````

I'm happy to help you with SwiftMessages issues, but this question is largely a Swift programming question and for that I suggest you try posting on Stack Overflow.
